Create movie pagination and filter
jgoh120/movie-collector-api pull request #19
Opened 2020-10-30 02:22 UTC by jgoh120

create pagination and filter based on avg rating and genre choice.

2020-11-01 14:01 UTC, clarencecastillo requested changes

2020-11-01 14:01 UTC, clarencecastillo commented on routers/movie.router.js
> +        genre: _.get(req.query, 'filterGenre', null)
We expect a value like `horror,comedy` from the request query. Hence, we'll need to convert the string value into an array like so:
`genres: _.get(req.query, 'filterGenres', '').split(',')`

2020-11-05 03:31 UTC, jgoh120 commented on controllers/movie.controller.js
> +    async getPageOfChoice(pagination, filter){
Done

2020-11-05 03:40 UTC, jgoh120 commented
all done

2020-11-08 12:20 UTC, clarencecastillo requested changes

2020-11-08 12:20 UTC, clarencecastillo commented on controllers/movie.controller.js
> +        return movies.map(r => this.formatMovie);
Rename local variable `r` into `m` and pass it as argument to `formatMovie` method.

2020-11-08 12:20 UTC, clarencecastillo commented on routers/movie.router.js
>  var reviewRouter = require('./review.router');
We need to import lodash first before we can use it:
`const _ = require('lodash');`

2020-11-08 12:20 UTC, clarencecastillo commented on controllers/movie.controller.js
> +            if (filter.genres != null) {
Rename the attribute `genres` to be just `genre` according to schema definition.

2020-11-08 13:42 UTC, clarencecastillo approved these changes

2020-11-08 13:42 UTC, merged